[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "aind-flatfield-correction"
description = "Package for flatfield correction in microscopic images"
license = "MIT"
requires-python = ">=3.10,<3.12"
authors = [
    {name = "Allen Institute for Neural Dynamics"}
]
classifiers = [
    "Programming Language :: Python :: 3"
]
readme = "README.md"
version = "1.0.0"

dependencies = [
    "numpy==1.24.2",
    "dask[distributed]",
    "boto3",
    "s3fs",
    "scikit-image",
    "matplotlib",
    "tifffile",
    "psutil",
    "BaSiCPy==1.1.0",
    "jax==0.4.23",
    "jaxlib==0.4.23",
    "zarr==2.18.2",
    "numcodecs<0.16",
    "natsort==8.4.0",
    "hyperactive==4.6.0",
    "gradient-free-optimizers<1.9.0",
    "aind-large-scale-prediction @ git+https://github.com/AllenNeuralDynamics/aind-large-scale-prediction.git@unpinned-versions",
]

[dependency-groups]
dev = [
    'black',
    'coverage',
    'flake8',
    'interrogate',
    'isort',
    'Sphinx',
    'furo'
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.black]
line-length = 79
target_version = ['py310']
exclude = '''

(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | build
    | dist
    | .conda
  )/
  | .gitignore
)
'''

[tool.coverage.run]
omit = ["*__init__*"]
source = ["aind_flatfield_correction", "tests"]

[tool.coverage.report]
exclude_lines = [
    "if __name__ == .__main__.:",
    "^from .* import .*",
    "^import .*",
    "pragma: no cover"
]
fail_under = 100

[tool.isort]
line_length = 79
profile = "black"
skip = [".conda", ".venv"]

[tool.interrogate]
exclude = ["setup.py", "docs", "build", ".conda"]
fail-under = 100
